name: Check formatting

on:
  pull_request:
    branches: [ main ]

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Check fmt
           run: deno fmt --check
